apiVersion: v1
kind: Pod
metadata:
  name: products-api
  labels:
    component: backend
spec:
  containers:
    - name: store-backend
      image: matnow138/backend:1.0.4
      command: ["bash","-c"]
      args: ["./gradlew build --info ; java -jar build/libs/products-api-0.0.1-SNAPSHOT.jar"]
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: database-configmap
        - secretRef:
            name: database-secret
      env:
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USERNAME
          value: kodilla
        - name: RABBITMQ_HOST
          value: "rabbitmq-cluster-ip-service"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_QUEUE_NAME
          value: "QUEUE"
